### PR TITLE
Add filter by category functionality to search

### PR DESCRIPTION
**Pull request by R-Eli-Levasseur**
Adds the filter by category functionality to search

### CODE REVIEW

**Comment by leong96** [comment]
@eguy006 Added two commits in, there was a conflict in forms.py, please double check that I didn't screw your code up.

Otherwise, your stuff looks fine. Perhaps their might be a way to incorporate the current category table into your code in forms.py? Maybe that's something for the back end meeting.

**Comment by R-Eli-Levasseur** [comment]
I don't see anything wrong with forms.py in the changed files tab, what did you commit?

**Comment by nlMeminger** [comment]
building the container results in an app unable to start with this stack trace:

root@33d5a1932d8b:/app# python3 manage.py runserver 0.0.0.0:8000
Performing system checks...

System check identified no issues (0 silenced).
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/utils/autoreload.py", line 54, in wrapper
    fn(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/commands/runserver.py", line 120, in inner_run
    self.check_migrations()
  File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 453, in check_migrations
    executor = MigrationExecutor(connections[DEFAULT_DB_ALIAS])
  File "/usr/local/lib/python3.6/site-packages/django/db/migrations/executor.py", line 18, in __init__
    self.loader = MigrationLoader(self.connection)
  File "/usr/local/lib/python3.6/site-packages/django/db/migrations/loader.py", line 49, in __init__
    self.build_graph()
  File "/usr/local/lib/python3.6/site-packages/django/db/migrations/loader.py", line 274, in build_graph
    raise exc
  File "/usr/local/lib/python3.6/site-packages/django/db/migrations/loader.py", line 248, in build_graph
    self.graph.validate_consistency()
  File "/usr/local/lib/python3.6/site-packages/django/db/migrations/graph.py", line 195, in validate_consistency
    [n.raise_error() for n in self.node_map.values() if isinstance(n, DummyNode)]
  File "/usr/local/lib/python3.6/site-packages/django/db/migrations/graph.py", line 195, in <listcomp>
    [n.raise_error() for n in self.node_map.values() if isinstance(n, DummyNode)]
  File "/usr/local/lib/python3.6/site-packages/django/db/migrations/graph.py", line 58, in raise_error
    raise NodeNotFoundError(self.error_message, self.key, origin=self.origin)
django.db.migrations.exceptions.NodeNotFoundError: Migration grasa_event_locator.0002_auto_20191008_1721 dependencies reference nonexistent parent node ('grasa_event_locator', '0001_initial')

**Comment by leong96** [comment]
Password reset stuff, and one change to make it so pending users do not appear in the all users list.

**Review by leong96 — APPROVED** [review]
From what I see, all changes are either from Eli or myself. No issues here.

**Review by justwheel — APPROVED** [review]
I didn't comb this closely, but I skimmed. I'm mostly relying on @leong96's passing review for this PR.

Since there is a lot depending on this PR, I'm going to go ahead and merge it so we can move on and iterate changes faster. Thanks @leong96 and @eguy006 for your hard work on this PR. :raised_hands:

**Pull request merged**
