### PR TITLE
Updated resetPWForm.php

### PR DESCRIPTION
**Pull request by leiyinmon**

### CODE REVIEW

**Comment by leong96** [comment]
@leiyinmon Note that the header and footer are now html files, so the .php had to be switched over. I've made a commit for that in this branch.

**Comment by justwheel** [comment]
@leiyinmon I forgot what this PR is for, could you please explain your changes?

I rebased this PR on `master`, but I think @ldidonato should review and sign-off on this PR before merging.

**Comment by nlMeminger** [comment]
@leiyinmon you also have some conflicts.  Could you please resolve them

**Comment by justwheel** [comment]
> @leiyinmon you also have some conflicts. Could you please resolve them

I just rebased it.

**Comment by leiyinmon** [comment]
I added the validation for resetPWForm, there was no validation originally.
I can't work on Merge conflicts until our meeting because I am at work.

**Comment by nlMeminger** [comment]
Duplicated in #193

**Pull request closed without merging**
