### PR TITLE
Got generic formatting to work

### PR DESCRIPTION
**Pull request by R-Eli-Levasseur**
Got generic formatting (new lines, tabs, extra spaces, whatever the shift enter soft newline is, etc.) to work and display properly on event page.

### CODE REVIEW

**Review by justwheel — COMMENTED** [review]
It would be nice if the front-end piece here was prettier instead of monospace text. But if we have to live with it, it's okay. I'd like @ldidonato or @leiyinmon to look at this one and see if they have a clever way to make this look better ([here is a screenshot](https://github.com/jwflory/django-rit-grasa/issues/197#issuecomment-557683619)).

**Comment by R-Eli-Levasseur** [comment]
Styles are fixed, should be good to go

**Comment by leong96** [comment]
image
Yay :D

**Review by leong96 — APPROVED** [review]
Tested this setup. Bullets in particular work, as well as other funky formatting.

**Comment by justwheel** [comment]
Thanks for figuring out the styling, nice work! :+1:

**Pull request merged**
