### PR TITLE
More email implementation

### PR DESCRIPTION
**Pull request by leong96**
This PR moves the send_email to a function in a new functions.py file. Simply call send_email(address, subject, message) to send the email. If printed as done here, the function returns the number of emails sent (which in this project, should be "1").

Functions - moved send_email off into a function in a separate file.
Views - Added the approprate imports to get the function file. Then removed the send_mail function off here to become send_email in the functions file. Also fixed a bug in the reset process, a single quote was causing the reset string to not match. To demo, the send email function was also added to the login process. The user will get a "You logged in!" email upon login.

### CODE REVIEW

**Comment by nlMeminger** [comment]
Does resetting a password redirect the user to the login page?

**Comment by leong96** [comment]
@nlMeminger It does, yes.

Should clarify for the heck of it; if the passwords don't match, it'll stay on the change password page. All validation is still in effect as well.

**Comment by leong96** [comment]
Added latest migrations and the timestamp functionality. This also takes the admin@admin.admin address to grasatest@yahoo.com address, which is a real email address.

**Review by R-Eli-Levasseur — APPROVED** [review]
Reviewed with Harrison, looks all good

**Pull request merged**
