### PR TITLE
OPS

### PR DESCRIPTION
**Pull request by nlMeminger**
Fixing bug where docker-compose didn't actually start the app

### CODE REVIEW

**Comment by leong96** [comment]
Still getting an error, seems to now be when creating tables, see https://pastebin.com/iNJ2c28H.

docker-compose up command is line 322 onwards.

**Comment by nlMeminger** [comment]
@leong96 what platform are you testing this on? windows or linux?

**Comment by leong96** [comment]
@nlMeminger Windows 10.

**Comment by nlMeminger** [comment]
Can you try making a linux VM and try building it there?

**Comment by leong96** [comment]
When I get back home tonight, yup.

**Pull request closed without merging**
