### PR TITLE
Switch PHP extensions to HTML (closes #156)

### LINKED ISSUE #156: Switch PHP file extensions to HTML
# Summary

Replace all file extensions from PHP to HTML

# Background

There is no actual PHP code remaining in our project; we should make sure the PHP file extensions are changed to HTML extensions so we don't falsely imply we are using PHP, when we are not.

# Details

This requires a front-end change (i.e. changing the actual file extensions) and a back-end change (i.e. making sure no links break). For the most part, this should be prevented by using `reverse()` method to look up a page URL by its page name.

# Outcome

No false implication that there is PHP in our stack, when there is not PHP in our stack

### PR DESCRIPTION
**Pull request by justwheel**
This commit is a large commit, but it refactors our files and code to
change any existing PHP file extension to an HTML extension. This
required a few changes, but here's the process I tried to follow:

1. Deleted `index.php` - seems like a duplicate of `search/search.html`?
2. If possible, wrap a page up into a `reverse()` method.
3. Change hard-coded pointers to PHP pages to updated HTML path

This could use testing and I left comments in some areas of the
front-end code that I wasn't sure about.

Closes #156.

### CODE REVIEW

**Comment by leong96** [comment]
@jwflory Something to note, there are several pull requests in here (mine, for better or worse), that do alter some code in the webpages while they had the php extension. They are for the most part, small edits, but we should double check with each other what those are before going ahead with this so there are not php and html files both in master that will need to get removed later. Opinion on that?

**Comment by justwheel** [comment]
@leong96 Now that your PRs merged to `master`, I rebased this pull request on top of the latest changes. I updated your changes with the PHP extensions to the HTML pages.

Most of the close review should be on the [`views.py` (see diff here)](https://github.com/jwflory/django-rit-grasa/pull/169/files#diff-07bcfeb1fc65295658b0b10590b823f9) changes, since this is what is most relevant to the back-end. My editor trimmed off hanging whitespace in a lot of the front-end files and it made the overall PR diff hard to read.

**Review by leong96 — APPROVED** [review]
Syntax looks fine.

**Comment by justwheel** [comment]
@nlMeminger When you have a moment, could you please rebuild this PR on staging and drop a link here?

**Pull request merged**
