### PR TITLE
docs: Outline Event Curation System docs, add Provider-specific

### PR DESCRIPTION
**Pull request by justwheel**
Part of #191.

This commit adds Event Curation System user documentation. The pages for
providers are finished. Pages for admins are still in progress, but are
added in this commit for the internal links used in the finished pages.

Screenshot: "How to register a Provider account" page

Screenshot: "How to create a new Event" page

Screenshot: "How to edit an existing Event" page

### CODE REVIEW

**Comment by leong96** [comment]
@jwflory Just one thing I'd like to suggest. In the section on editing events, you indicate that it is not recommended to edit an event which already has a pending edit. Might I suggest specifically explaining to the reader why; or explaining what will happen if an additional edit is created?

**Comment by justwheel** [comment]
@leong96 Good feedback. See if my change in commit 5faa750624b9498d3031518f4b39896e82393a78 addresses your feedback. Feel free to approve and merge if it does.

**Comment by justwheel** [comment]
@leong96 I think commit c6f0fcdeeef4922f17509164049ffb90cd42ac68 is more direct, what do you think?

**Review by leong96 — APPROVED** [review]
Requested some changes to wording, but it does the trick now. Thanks!

**Pull request merged**
